// Constants: used for drawing/positioning graphics
ROAD_WIDTH = 1000;
ROAD_HEIGHT = 300;
CAR_WIDTH = 100;
CAR_HEIGHT = 50;
MID_Y = ROAD_HEIGHT/2 - CAR_HEIGHT/2;
TOP_LANE_Y = ROAD_HEIGHT/4 - CAR_HEIGHT/2;
BOTTOM_LANE_Y = ROAD_HEIGHT*3/4 - CAR_HEIGHT/2;
DX = 5;
